### ISSUE TITLE
Does this DNS tools (dnscontrol, octodns, denominator…) have their place in awesome DNS curated list?

### ISSUE THREAD

**Issue by harobed** [dnsplus/awesome-dns#1]
Hi,

I'm wondering if this DNS tools have their place in awesome DNS curated list?

* [dnscontrol](https://github.com/StackExchange/dnscontrol) - Synchronize your DNS to multiple providers from a simple DSL - by StackExchange
* [denominator](https://github.com/Netflix/denominator) - Portably control DNS clouds using java or bash - By Netfilx
* [octodns](https://github.com/github/octodns) - DNS as code - Tools for managing DNS across multiple providers - By GitHub
* [lexicon](https://github.com/AnalogJ/lexicon) - Manipulate DNS records on various DNS providers in a standardized way. 

See also: https://github.com/AcalephStorage/awesome-devops/issues/8

Best regards,
Stéphane

**Comment by idennydeng** [comment]
They would be useful. You can create a PR.
